[build]
  publish = "build"
  functions = "functions"

[dev]
  targetPort = 8081
  port = 8888
  functions = "functions"
  command = "yarn dev --port 8081"
  framework = "vite"
  autoLaunch = false
  
# Disable automatic SPA redirects during development
[dev.redirects]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
